export const ancientWorld = [
    {
        question: "Who was the first Pharaoh of Ancient Egypt?",
        a: {option: "The first Pharaoh of Ancient Egypt was Narmer (also known as Menes)", isCorrect: true},
        b: {option: "The first Pharaoh of Ancient Egypt was Akhenaten", isCorrect: false},
        c: {option: "The first Pharaoh of Ancient Egypt was Tutankhamun", isCorrect: false},
        d: {option: "The first Pharaoh of Ancient Egypt was Khufu", isCorrect: false},
    },
    {
        question: "What type of government did Ancient Rome have?",
        a: {option: "Monarchy", isCorrect: false},
        b: {option: "Democracy", isCorrect: false},
        c: {option: "Oligarchy", isCorrect: false},
        d: {option: "Republic", isCorrect: true},
    },
    {
        question: "What was the main religion of Ancient Rome?",
        a: {option: "Christianity", isCorrect: false},
        b: {option: "Paganism", isCorrect: true},
        c: {option: "Hinduism", isCorrect: false},
        d: {option: "Buddhism", isCorrect: false},
    },
    {
        question: "What was the primary form of literature during Ancient Greece?",
        a: {option: "Poetry", isCorrect: false},
        b: {option: "Prose", isCorrect: false},
        c: {option: "Drama", isCorrect: true},
        d: {option: "Non-Fiction", isCorrect: false},
    },
    {
        question: "What type of writing system did the Ancient Sumerians use?",
        a: {option: "Cuneiform", isCorrect: true},
        b: {option: "Hieroglyphics", isCorrect: false},
        c: {option: "Latin", isCorrect: false},
        d: {option: "Greek", isCorrect: false},
    },
    {
        question: "What was the most prominent religion in Ancient Mesopotamia?",
        a: {option: "Christianity", isCorrect: false},
        b: {option: "Judaism", isCorrect: false},
        c: {option: "Zoroastrianism", isCorrect: true},
        d: {option: "Paganism", isCorrect: false},
    },
    {
        question: "What was the main currency used in Ancient Rome?",
        a: {option: "Pesos", isCorrect: false},
        b: {option: "Dollars", isCorrect: false},
        c: {option: "Euros", isCorrect: false},
        d: {option: "Denarii", isCorrect: true},
    },
    {
        question: "What was the main metal used in Ancient Egyptian jewelry?",
        a: {option: "Gold", isCorrect: true},
        b: {option: "Silver", isCorrect: false},
        c: {option: "Copper", isCorrect: false},
        d: {option: "Tin", isCorrect: false},
    },
    {
        question: "What language were the Ancient Vedas written in??",
        a: {option: "Sanskrit", isCorrect: true},
        b: {option: "Latin", isCorrect: false},
        c: {option: "Greek", isCorrect: false},
        d: {option: "Hindi", isCorrect: false},
    },
    {
        question: "What was the primary source of entertainment in the Ancient World?",
        a: {option: "Sports", isCorrect: false},
        b: {option: "Music", isCorrect: false},
        c: {option: "Theater", isCorrect: true},
        d: {option: "Video Games", isCorrect: false},
    },
    {
        question: "Who was the first Roman emperor?",
        a: {option: "Julius Caesar", isCorrect: false},
        b: {option: "Augustus", isCorrect: true},
        c: {option: "Nero", isCorrect: false},
        d: {option: "Constantine", isCorrect: false},
    },
    {
        question: "Who was the first ruler of Ancient Greece?",
        a: {option: "Alexander the Great", isCorrect: false},
        b: {option: "Pericles", isCorrect: false},
        c: {option: "Cleisthenes", isCorrect: true},
        d: {option: "Hippocrates", isCorrect: false},
    },
    {
        question: "Who was the most powerful woman in Ancient Rome?",
        a: {option: "Livia", isCorrect: true},
        b: {option: "Agrippina", isCorrect: false},
        c: {option: "Julia", isCorrect: false},
        d: {option: "Cleopatra", isCorrect: false},
    },
    {
        question: "Who was the most powerful woman in Ancient Egypt?",
        a: {option: "Nefertiti", isCorrect: false},
        b: {option: "Hatshepsut", isCorrect: true},
        c: {option: "Cleopatra", isCorrect: false},
        d: {option: "Nefertari", isCorrect: false},
    },
    {
        question: "Who was the most famous Roman politician and orator?",
        a: {option: "Julius Caesar", isCorrect: false},
        b: {option: "Cicero", isCorrect: true},
        c: {option: "Augustus", isCorrect: false},
        d: {option: "Nero", isCorrect: false},
    },
]