export const jsQuestions = [
    {
        question: "What is JSON??",
        a: {option: "JavaScript Object Notation", isCorrect: true},
        b: {option: "JavaScript Observable Nature", isCorrect: false},
        c: {option: "JavaScript Obsessed Name", isCorrect: false},
        d: {option: "JavaScript Object Name", isCorrect: false},
    },
    {
        question: "The JavaScript operator to find the type of a JavaScript variable?",
        a: {option: "type-of", isCorrect: false},
        b: {option: "typeOf", isCorrect: false},
        c: {option: "typeof", isCorrect: true},
        d: {option: "type", isCorrect: false},
    },
    {
        question: "In JavaScript the maximum number of decimals is?",
        a: {option: "16", isCorrect: false},
        b: {option: "15", isCorrect: false},
        c: {option: "18", isCorrect: false},
        d: {option: "17", isCorrect: true},
    },
    {
        question: "JavaScript const variables must be...",
        a: {option: "Reassigned a value after they are declared", isCorrect: false},
        b: {option: "Redeclared", isCorrect: false},
        c: {option: "Assigned a value when they are declared", isCorrect: true},
        d: {option: "Reassigned a constant array", isCorrect: false},
    },
    {
        question: "In an object method, 'this' refers to the?",
        a: {option: "Array", isCorrect: false},
        b: {option: "String", isCorrect: false},
        c: {option: "Number", isCorrect: false},
        d: {option: "Object", isCorrect: true},
    },
    {
        question: "Await makes a function wait for?",
        a: {option: "A promise", isCorrect: true},
        b: {option: "An event", isCorrect: false},
        c: {option: "A JSON server", isCorrect: false},
        d: {option: "Pop up alert", isCorrect: false},
    },
    {
        question: "Math.round(x) returns x...",
        a: {option: "up to its nearest integer", isCorrect: false},
        b: {option: "rounded to its nearest integer", isCorrect: true},
        c: {option: "down to its nearest integer", isCorrect: false},
        d: {option: "Returns the integer part of x", isCorrect: false},
    },
    {
        question: "JavaScript BigInt variables are used to?",
        a: {option: "Store functions", isCorrect: false},
        b: {option: "Store array of numbers", isCorrect: false},
        c: {option: "Store big integer values that are too big to be represented by a normal JavaScript Number", isCorrect: true},
        d: {option: "Store number properties", isCorrect: false},
    },
    {
        question: "for/in loops?",
        a: {option: "Through the properties of an object", isCorrect: true},
        b: {option: "Through a block of code while a specified condition is true", isCorrect: false},
        c: {option: "Through a block of code a number of times", isCorrect: false},
        d: {option: "Through the values of an iterable object", isCorrect: false},
    },
    {
        question: "The Boolean value of 0 (zero) is?",
        a: {option: "String", isCorrect: false},
        b: {option: "Number", isCorrect: false},
        c: {option: "True", isCorrect: false},
        d: {option: "False", isCorrect: true},
    },
    {
        question: "A regular expression is a pattern of?",
        a: {option: "Boolean", isCorrect: false},
        b: {option: "Characters", isCorrect: true},
        c: {option: "JS Date", isCorrect: false},
        d: {option: "JS Classes", isCorrect: false},
    },
    {
        question: "JS Class properties are assigned inside...?",
        a: {option: "A function", isCorrect: false},
        b: {option: "A global variables", isCorrect: false},
        c: {option: "A constructor() method", isCorrect: true},
        d: {option: "Window navigator", isCorrect: false},
    },
    {
        question: "The Error object provides...?",
        a: {option: "Error information when an error occurs", isCorrect: true},
        b: {option: "Events that occur when the mouse interacts with the HTML document", isCorrect: false},
        c: {option: "Events that occur when a user navigates to or from a webpage", isCorrect: false},
        d: {option: "mouse buttons when the mouse event was triggered", isCorrect: false},
    },
    {
        question: "The charAt() method returns...?",
        a: {option: "The index of the first character", isCorrect: false},
        b: {option: "The index of the last character", isCorrect: false},
        c: {option: "The character at a specified index (position) in a string", isCorrect: true},
        d: {option: "The Unicode of the character at a specified index (position) in a string.", isCorrect: false},
    },
    {
        question: "What does the slice() method?",
        a: {option: "Extracts a part of a string", isCorrect: true},
        b: {option: "Splits a string into an array of substrings", isCorrect: false},
        c: {option: "Returns an array with the matches", isCorrect: false},
        d: {option: "Returns the length of a string", isCorrect: false},
    },
]