export const programQuestions = [
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your surname?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your second surname?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
    {
        question: "what is your name?",
        a: {option: "Rita", isCorrect: true},
        b: {option: "Samuel", isCorrect: false},
        c: {option: "Albert", isCorrect: false},
        d: {option: "Victor", isCorrect: false},
    },
]
